### ISSUE TITLE
`saved_model.pb` seems like broken.

### ISSUE THREAD

**Issue by Reemann** [mueller-lab/TwinNet#2]
Hi! I'm trying to use your segmentation model. However, the `saved_model.pb` file under the `TwinNet/data/segmentation_model/saved_model` directory seems broken because I got this error when trying to load it in with the `tf.saved_model.load()` function:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 858, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 988, in load_partial
    loader = Loader(object_graph_proto, saved_model_proto, export_dir,
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 205, in __init__
    self._restore_checkpoint()
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 540, in _restore_checkpoint
    load_status = saver.restore(variables_path, self._checkpoint_options)
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 1422, in restore
    object_graph_string = reader.get_tensor(base.OBJECT_GRAPH_PROTO_KEY)
  File "/mnt/Storage/home/.../anaconda3/envs/jupyter_kernel/lib/python3.9/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 66, in get_tensor
    return CheckpointReader.CheckpointReader_GetTensor(
IndexError: Read less bytes than requested
```

In an effort to resolve this issue, I have attempted to re-download the saved_model.pb file from your repository. Despite this, the error persists. Additionally, I observed that this file had been previously re-uploaded due to an issue with its initial upload:
<img width="595" alt="image" src="https://github.com/mueller-lab/TwinNet/assets/74175760/89f225e3-c211-4704-b64b-a94859bbb75f">

I would greatly appreciate it if you could verify the proper re-upload of the saved_model.pb file. It seems there might still be an issue with the current version, despite the re-upload effort. Your attention to this detail would be incredibly helpful in resolving the loading error I'm encountering.

**Comment by hernanmorales-navarrete** [comment]
Hi [Reemann](https://github.com/Reemann),
Thanks for reporting the issue. We re-uploaded the saved_model.pb file.
Additionally, we added an README with a link for the [Tutorial Data](https://cloud.uni-konstanz.de/index.php/s/mCWq75Eg5cXQPA4) where the models can be also downloaded -particularly suggested for large files like the pre-trained models: https://github.com/mueller-lab/TwinNet/blob/main/data/README.md
